<?php

/**
 * @file
 * Main file for the Islandora module. 
 * 
 * This file registers the menu paths and calls the view hooks
 * for Islandora 7 core. 
 */

/**
 * Implements hook_menu().
 */
function islandora_menu() {
  $items = array();

  // islandora setup page
  $items['admin/config/content/islandora'] = array(
    'title' => 'Islandora Settings',
    'description' => 'Configure Islandora and all its related modules.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_admin_settings'),
    'access arguments' => array('islandora administrator'),
    'file' => 'islandora.admin.inc',
  );

  // main islandora page - this is an implicit view of the top level collection
  $items['islandora'] = array(
    'title' =>  variable_get('islandora_repository_title', 'Islandora'),
    'page callback' => 'islandora_view_object',
    'access arguments' => array('islandora view object'),
    'type' => MENU_NORMAL_ITEM,
  );

  // islandora/{pid} - this is an implicit view of the object
  $items['islandora/%islandora_object'] = array(
    'title' => 'View Islandora Object',
    'page callback' => 'islandora_view_object',
    'type' => MENU_CALLBACK,
    'access arguments' => array('islandora view object')
  );

  // islandora/{pid}/view - view an object
  $items['islandora/%islandora_object/view'] = array(
    'title' => 'View Islandora Object',
    'page callback' => 'islandora_view_object',
    'type' => MENU_CALLBACK,
    'access arguments' => array('islandora view object')
  );

  // islandora/{pid}/view/{dsid} - view a datastream
  $items['islandora/%islandora_object/view/%'] = array(
    'title' => 'View Islandora Datastream',
    'page callback' => 'islandora_view_datastream',
    'page arguments' => array(1, 3),
    'type' => MENU_CALLBACK,
    'access arguments' => array('islandora view object')
  );

  // islandora/{pid}/download/{dsid} - download a datastream
  $items['islandora/%islandora_object/download/%'] = array(
    'title' => 'Download Islandora Datastream',
    'page callback' => 'islandora_download_datastream',
    'page arguments' => array(1, 3),
    'type' => MENU_CALLBACK,
    'access arguments' => array('islandora view object')
  );

  // islandora/{pid}/addDatastream - add a datastream to an object
  $items['islandora/%islandora_object/addDatastream'] = array(
    'title' => 'Add a datastream to an object',
    'page callback' => 'islandora_download_datastream',
    'page arguments' => array(1, 3),
    'type' => MENU_CALLBACK,
    'access arguments' => array('islandora add datastream')
  );

  // islandora/{pid}/purge - purge an object
  $items['islandora/%islandora_object/purge'] = array(
    'title' => 'Add a datastream to an object',
    'page callback' => 'islandora_download_datastream',
    'page arguments' => array(1, 3),
    'type' => MENU_CALLBACK,
    'access arguments' => array('islandora purge')
  );

  
  return $items;
}

/**
 * Implements hook_permission().
 * 
 * This function registers the following permissions:
 *  - islandora view objects
 *  - islandora edit object (includes metadata)
 *  - islandora purge (both objects and datastreams)
 *  - islandora add object
 *  - islandora add datastream
 *  - islandora administrator
 */
function islandora_permission() {
  $permissions = array();
  $permissions['islandora view object'] = array(
    'title' => t('View Islandora Objects.'),
    'description' => t('Allow the user to view object in the repository through Islandora.'),
  );
  $permissions['islandora edit object'] = array(
    'title' => t('Edit Islandora Metadata.'),
    'description' => t('Allow the user to edit object (status, etc) and metadata through Islandora.'),
  );
  $permissions['islandora add object'] = array(
    'title' => t('Add Islandora Objects.'),
    'description' => t('Allow the user to add new objects to Islandora.'),
  );
  $permissions['islandora add datastream'] = array(
    'title' => t('Add Islandora Datastreams.'),
    'description' => t('Allow the user to add new datastreams to Islandora.'),
  );
  $permissions['islandora purge'] = array(
    'title' => t('Purge Objects and Datastreams.'),
    'description' => t('Allow the user to purge (completely delete) object and datastreams from Islandora.'),
    'restrict access' => TRUE,
  );
  $permissions['islandora administrator'] = array(
    'title' => t('Administer Islandora.'),
    'description' => t('Allow the user to configure Islandora and its related modules.'),
    'restrict access' => TRUE,
  );
  return $permissions;
}
